version: "3"

networks:
  docker_lecturen:
    external: true

services:
  application:
    container_name: app
    image: northkillz/application:1.0.0
    networks:
      - docker_lecturen
    volumes:
      - ../../crypto:/srv/application/crypto
      - ./wallet:/srv/application/wallet
    command: sh -c "node ./setup.js && node ./run.js"
